--DROP TABLE datalake.additional_decisions;
CREATE TABLE IF NOT EXISTS datalake.additional_decisions
(
	investigation_id BIGINT   ENCODE RAW
	,decision_id VARCHAR(36)   ENCODE lzo
	,original_decision VARCHAR(32)   ENCODE lzo
	,additional_decision VARCHAR(32)   ENCODE lzo
	,added_by BIGINT   ENCODE RAW
	,user_role VARCHAR(32)   ENCODE lzo
	,started_at TIMESTAMP WITH TIME ZONE   ENCODE lzo
	,decided_at TIMESTAMP WITH TIME ZONE   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	, added_by
	)
;
--DROP TABLE datalake.additional_review_notes;
CREATE TABLE IF NOT EXISTS datalake.additional_review_notes
(
	investigation_id BIGINT   ENCODE RAW
	,decision_id VARCHAR(36)   ENCODE RAW
	,added_by BIGINT   ENCODE lzo
	,user_role VARCHAR(32)   ENCODE lzo
	,added_at TIMESTAMP WITH TIME ZONE   ENCODE lzo
	,text VARCHAR(1000)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	, decision_id
	)
;
--DROP TABLE datalake.billing_to_recipients_whitepages_identity_check;
CREATE TABLE IF NOT EXISTS datalake.billing_to_recipients_whitepages_identity_check
(
	investigation_id BIGINT   ENCODE RAW
	,identity_check_idx INTEGER   ENCODE lzo
	,primary_phone_checks_error_message VARCHAR(65535)   ENCODE lzo
	,primary_phone_checks_error_name VARCHAR(65535)   ENCODE lzo
	,primary_phone_checks_warning VARCHAR(65535)   ENCODE lzo
	,primary_phone_checks_is_valid BOOLEAN   ENCODE RAW
	,primary_phone_checks_to_name VARCHAR(65535)   ENCODE bytedict
	,primary_phone_checks_to_address VARCHAR(65535)   ENCODE bytedict
	,primary_phone_checks_subscriber_name VARCHAR(65535)   ENCODE lzo
	,primary_phone_checks_subscriber_age_range VARCHAR(65535)   ENCODE bytedict
	,primary_phone_checks_country_code VARCHAR(65535)   ENCODE bytedict
	,primary_phone_checks_is_commercial BOOLEAN   ENCODE RAW
	,primary_phone_checks_line_type VARCHAR(65535)   ENCODE bytedict
	,primary_phone_checks_carrier VARCHAR(65535)   ENCODE lzo
	,primary_phone_checks_is_prepaid BOOLEAN   ENCODE RAW
	,secondary_phone_checks_error_message VARCHAR(65535)   ENCODE lzo
	,secondary_phone_checks_error_name VARCHAR(65535)   ENCODE lzo
	,secondary_phone_checks_warning VARCHAR(65535)   ENCODE lzo
	,secondary_phone_checks_is_valid BOOLEAN   ENCODE RAW
	,secondary_phone_checks_to_name VARCHAR(65535)   ENCODE bytedict
	,secondary_phone_checks_to_address VARCHAR(65535)   ENCODE bytedict
	,secondary_phone_checks_subscriber_name VARCHAR(65535)   ENCODE lzo
	,secondary_phone_checks_subscriber_age_range VARCHAR(65535)   ENCODE bytedict
	,secondary_phone_checks_country_code VARCHAR(65535)   ENCODE bytedict
	,secondary_phone_checks_is_commercial BOOLEAN   ENCODE RAW
	,secondary_phone_checks_line_type VARCHAR(65535)   ENCODE bytedict
	,secondary_phone_checks_carrier VARCHAR(65535)   ENCODE lzo
	,secondary_phone_checks_is_prepaid BOOLEAN   ENCODE RAW
	,primary_address_checks_error_message VARCHAR(65535)   ENCODE lzo
	,primary_address_checks_error_name VARCHAR(65535)   ENCODE lzo
	,primary_address_checks_warnings VARCHAR(65535)   ENCODE lzo
	,primary_address_checks_is_valid BOOLEAN   ENCODE RAW
	,primary_address_checks_diagnostics VARCHAR(65535)   ENCODE lzo
	,primary_address_checks_is_active BOOLEAN   ENCODE RAW
	,primary_address_checks_to_name VARCHAR(65535)   ENCODE bytedict
	,primary_address_checks_resident_name VARCHAR(65535)   ENCODE lzo
	,primary_address_checks_resident_age_range VARCHAR(65535)   ENCODE bytedict
	,primary_address_checks_is_resident_deceased BOOLEAN   ENCODE RAW
	,primary_address_checks_is_commercial BOOLEAN   ENCODE RAW
	,primary_address_checks_is_forwarder BOOLEAN   ENCODE RAW
	,primary_address_checks_type VARCHAR(65535)   ENCODE bytedict
	,secondary_address_checks_error_message VARCHAR(65535)   ENCODE lzo
	,secondary_address_checks_error_name VARCHAR(65535)   ENCODE lzo
	,secondary_address_checks_warnings VARCHAR(65535)   ENCODE lzo
	,secondary_address_checks_is_valid BOOLEAN   ENCODE RAW
	,secondary_address_checks_diagnostics VARCHAR(65535)   ENCODE lzo
	,secondary_address_checks_is_active BOOLEAN   ENCODE RAW
	,secondary_address_checks_to_name VARCHAR(65535)   ENCODE bytedict
	,secondary_address_checks_resident_name VARCHAR(65535)   ENCODE lzo
	,secondary_address_checks_resident_age_range VARCHAR(65535)   ENCODE bytedict
	,secondary_address_checks_is_resident_deceased BOOLEAN   ENCODE RAW
	,secondary_address_checks_is_commercial BOOLEAN   ENCODE RAW
	,secondary_address_checks_is_forwarder BOOLEAN   ENCODE RAW
	,secondary_address_checks_type VARCHAR(65535)   ENCODE bytedict
	,email_address_checks_error_message VARCHAR(65535)   ENCODE lzo
	,email_address_checks_error_name VARCHAR(65535)   ENCODE lzo
	,email_address_checks_warnings VARCHAR(65535)   ENCODE lzo
	,email_address_checks_is_valid BOOLEAN   ENCODE RAW
	,email_address_checks_diagnostics VARCHAR(65535)   ENCODE lzo
	,email_address_checks_is_autogenerated BOOLEAN   ENCODE RAW
	,email_address_checks_is_disposable BOOLEAN   ENCODE RAW
	,email_address_checks_to_name VARCHAR(65535)   ENCODE bytedict
	,email_address_checks_registered_name VARCHAR(65535)   ENCODE lzo
	,email_address_checks_registered_owner_age_range VARCHAR(65535)   ENCODE bytedict
	,email_address_checks_first_seen_date VARCHAR(65535)   ENCODE lzo
	,email_address_checks_first_seen_days BIGINT   ENCODE lzo
	,email_address_checks_domain_creation_date VARCHAR(65535)   ENCODE lzo
	,email_address_checks_domain_creation_days BIGINT   ENCODE lzo
	,ip_address_checks_error_message VARCHAR(65535)   ENCODE lzo
	,ip_address_checks_error_name VARCHAR(65535)   ENCODE lzo
	,ip_address_checks_warnings VARCHAR(65535)   ENCODE lzo
	,ip_address_checks_is_valid BOOLEAN   ENCODE RAW
	,ip_address_checks_geolocation_postal_code VARCHAR(65535)   ENCODE lzo
	,ip_address_checks_geolocation_city_name VARCHAR(65535)   ENCODE lzo
	,ip_address_checks_geolocation_country_name VARCHAR(65535)   ENCODE bytedict
	,ip_address_checks_geolocation_continent_code VARCHAR(65535)   ENCODE bytedict
	,ip_address_checks_geolocation_country_code VARCHAR(65535)   ENCODE bytedict
	,ip_address_checks_is_proxy BOOLEAN   ENCODE RAW
	,ip_address_checks_distance_from_address BIGINT   ENCODE lzo
	,ip_address_checks_distance_from_phone BIGINT   ENCODE lzo
	,ip_address_checks_connection_type VARCHAR(65535)   ENCODE bytedict
	,identity_check_score BIGINT   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.browser_ip;
CREATE TABLE IF NOT EXISTS datalake.browser_ip
(
	investigation_id BIGINT   ENCODE RAW
	,raw_browser_ip VARCHAR(65535)   ENCODE lzo
	,browser_ip VARCHAR(65535)   ENCODE lzo
	,browser_ip_oh_key VARCHAR(65535)   ENCODE lzo
	,mm_city_confidence INTEGER   ENCODE lzo
	,mm_city_geoname_id INTEGER   ENCODE lzo
	,mm_city_name_en VARCHAR(65535)   ENCODE lzo
	,mm_continent_code CHAR(4096)   ENCODE lzo
	,mm_continent_geoname_id INTEGER   ENCODE lzo
	,mm_continent_name_en VARCHAR(65535)   ENCODE lzo
	,mm_country_confidence INTEGER   ENCODE lzo
	,mm_country_geoname_id INTEGER   ENCODE lzo
	,mm_country_iso_code CHAR(4096)   ENCODE lzo
	,mm_country_name_en VARCHAR(65535)   ENCODE lzo
	,mm_location_accuracy_radius INTEGER   ENCODE lzo
	,mm_location_latitude DOUBLE PRECISION   ENCODE RAW
	,mm_location_longitude DOUBLE PRECISION   ENCODE RAW
	,mm_location_time_zone VARCHAR(65535)   ENCODE lzo
	,mm_postal_confidence INTEGER   ENCODE lzo
	,mm_postal_code VARCHAR(65535)   ENCODE lzo
	,mm_registered_country_iso_code CHAR(4096)   ENCODE lzo
	,mm_registered_country_geoname_id INTEGER   ENCODE lzo
	,mm_registered_country_name_en VARCHAR(65535)   ENCODE lzo
	,mm_user_type VARCHAR(65535)   ENCODE lzo
	,mm_autonomous_system_number INTEGER   ENCODE lzo
	,mm_autonomous_system_organization VARCHAR(65535)   ENCODE lzo
	,mm_domain_name VARCHAR(65535)   ENCODE lzo
	,mm_isp VARCHAR(65535)   ENCODE lzo
	,mm_organization VARCHAR(65535)   ENCODE lzo
	,mm_ip_address VARCHAR(65535)   ENCODE lzo
	,mm_proxy_score DOUBLE PRECISION   ENCODE RAW
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.chargebacks;
CREATE TABLE IF NOT EXISTS datalake.chargebacks
(
	investigation_id BIGINT   ENCODE RAW
	,chargeback_id BIGINT   ENCODE lzo
	,chargeback_merchant_order_id VARCHAR(65535)   ENCODE lzo
	,chargeback_payment_processor VARCHAR(65535)   ENCODE lzo
	,chargeback_ref_id VARCHAR(65535)   ENCODE lzo
	,chargeback_reason_proc VARCHAR(65535)   ENCODE lzo
	,chargeback_reason_proc_code VARCHAR(65535)   ENCODE lzo
	,chargeback_reason_proc_desc VARCHAR(65535)   ENCODE lzo
	,chargeback_normalized_reason VARCHAR(65535)   ENCODE lzo
	,chargeback_amount_currency VARCHAR(65535)   ENCODE lzo
	,chargeback_raw_amount VARCHAR(65535)   ENCODE lzo
	,chargeback_normalized_amount NUMERIC(20,4)   ENCODE lzo
	,chargeback_fees_currency VARCHAR(65535)   ENCODE lzo
	,chargeback_raw_fees VARCHAR(65535)   ENCODE lzo
	,chargeback_normalized_fees NUMERIC(20,4)   ENCODE lzo
	,chargeback_issuer_reported_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_signifyd_reported_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_source_detection VARCHAR(65535)   ENCODE lzo
	,chargeback_stage VARCHAR(65535)   ENCODE lzo
	,chargeback_order_match VARCHAR(65535)   ENCODE lzo
	,claim_amount NUMERIC(20,4)   ENCODE lzo
	,claim_amount_currency VARCHAR(65535)   ENCODE lzo
	,claim_customer_id BIGINT   ENCODE lzo
	,claim_status VARCHAR(65535)   ENCODE lzo
	,claim_disposition VARCHAR(65535)   ENCODE lzo
	,claim_disposition_reason VARCHAR(65535)   ENCODE lzo
	,claim_notes VARCHAR(65535)   ENCODE lzo
	,claim_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,claim_created_by BIGINT   ENCODE lzo
	,claim_created_by_type VARCHAR(65535)   ENCODE lzo
	,claim_updated_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,claim_updated_by BIGINT   ENCODE lzo
	,claim_updated_by_type VARCHAR(65535)   ENCODE lzo
	,claim_document_urls VARCHAR(65535)   ENCODE lzo
	,representment_id BIGINT   ENCODE lzo
	,representment_type VARCHAR(65535)   ENCODE lzo
	,representment_status VARCHAR(65535)   ENCODE lzo
	,representment_status_reason VARCHAR(65535)   ENCODE lzo
	,representment_outcome VARCHAR(65535)   ENCODE lzo
	,representment_respond_deadline TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,representment_score INTEGER   ENCODE lzo
	,representment_assigned_agent_user_id BIGINT   ENCODE lzo
	,representment_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,representment_updated_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,representment_updated_by BIGINT   ENCODE lzo
	,representment_updated_by_type VARCHAR(65535)   ENCODE lzo
	,claim_disposition_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,claim_adjusted_chargeback_amount NUMERIC(20,4)   ENCODE lzo
	,claim_adjusted_chargeback_amount_exchange_rate NUMERIC(20,10)   ENCODE lzo
	,claim_adjusted_chargeback_fee NUMERIC(20,4)   ENCODE lzo
	,claim_adjusted_chargeback_fee_exchange_rate NUMERIC(20,10)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.exchange_rates_full;
CREATE TABLE IF NOT EXISTS datalake.exchange_rates_full
(
	base_iso4217_currency_code VARCHAR(3) NOT NULL  ENCODE RAW
	,target_iso4217_currency_code VARCHAR(3)   ENCODE lzo
	,rate_date DATE   ENCODE delta
	,rate DOUBLE PRECISION   ENCODE RAW
	,source VARCHAR(255)   ENCODE lzo
	,created_at TIMESTAMP WITH TIME ZONE   ENCODE delta
	,PRIMARY KEY (base_iso4217_currency_code)
)
DISTSTYLE KEY
 DISTKEY (base_iso4217_currency_code)
 SORTKEY (
	base_iso4217_currency_code
	)
;
--DROP TABLE datalake.fulfillments;
CREATE TABLE IF NOT EXISTS datalake.fulfillments
(
	investigation_id BIGINT   ENCODE RAW
	,id VARCHAR(65535)   ENCODE lzo
	,order_id VARCHAR(65535)   ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,delivery_email VARCHAR(65535)   ENCODE lzo
	,fulfillment_status VARCHAR(65535)   ENCODE lzo
	,tracking_numbers VARCHAR(65535)   ENCODE lzo
	,tracking_urls VARCHAR(65535)   ENCODE lzo
	,shipment_status VARCHAR(65535)   ENCODE lzo
	,delivery_address_full_address VARCHAR(65535)   ENCODE lzo
	,delivery_address_street_address VARCHAR(65535)   ENCODE lzo
	,delivery_address_unit VARCHAR(65535)   ENCODE lzo
	,delivery_address_city VARCHAR(65535)   ENCODE lzo
	,delivery_address_province_code VARCHAR(65535)   ENCODE lzo
	,delivery_address_postal_code VARCHAR(65535)   ENCODE lzo
	,delivery_address_country_code VARCHAR(65535)   ENCODE lzo
	,delivery_address_latitude DOUBLE PRECISION   ENCODE RAW
	,delivery_address_longitude DOUBLE PRECISION   ENCODE RAW
	,recipient_name VARCHAR(65535)   ENCODE lzo
	,confirmation_name VARCHAR(65535)   ENCODE lzo
	,confirmation_phone VARCHAR(65535)   ENCODE lzo
	,shipping_carrier VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.investigations;
CREATE TABLE IF NOT EXISTS datalake.investigations
(
	investigation_id BIGINT NOT NULL  ENCODE RAW
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE RAW
	,updated_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,checkout_token VARCHAR(500)   ENCODE lzo
	,created_by_user_id BIGINT   ENCODE lzo
	,credit_card_amount NUMERIC(20,4)   ENCODE lzo
	,customer_id BIGINT   ENCODE lzo
	,customer_order_recommendation VARCHAR(500)   ENCODE lzo
	,customer_submit_for_guarantee_indicator BOOLEAN   ENCODE RAW
	,exchange_rate DOUBLE PRECISION   ENCODE RAW
	,exchange_rate_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,gift_card_amount NUMERIC(20,4)   ENCODE lzo
	,guarantee_id BIGINT   ENCODE lzo
	,guarantee_disposition VARCHAR(500)   ENCODE lzo
	,guarantee_reviewed_by BIGINT   ENCODE lzo
	,guarantee_user_submitted_by BIGINT   ENCODE lzo
	,guarantee_team_submitted_by BIGINT   ENCODE lzo
	,guarantee_submitted_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,guarantee_reviewed_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,guarantee_score DOUBLE PRECISION   ENCODE RAW
	,guarantee_model_id VARCHAR(500)   ENCODE lzo
	,guarantee_auto_decision_reason VARCHAR(500)   ENCODE lzo
	,guarantee_plan_type VARCHAR(500)   ENCODE lzo
	,guarantee_auto_submission_policy VARCHAR(500)   ENCODE lzo
	,guarantee_submission_policy_id BIGINT   ENCODE lzo
	,guarantee_review_deadline TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,guarantee_review_timeout_disposition VARCHAR(500)   ENCODE lzo
	,guarantee_review_timeout_decision_reason VARCHAR(500)   ENCODE lzo
	,guarantee_decision_count BIGINT   ENCODE mostly8
	,guarantee_max_review_sla_in_ms BIGINT   ENCODE lzo
	,guarantee_nominal_review_sla_in_ms BIGINT   ENCODE lzo
	,guarantee_review_escalation_level BIGINT   ENCODE lzo
	,investigation_review_disposition VARCHAR(500)   ENCODE lzo
	,investigation_review_disposition_set_by BIGINT   ENCODE lzo
	,investigation_status VARCHAR(500)   ENCODE lzo
	,is_test_investigation BOOLEAN   ENCODE RAW
	,normalized_purchase_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,order_channel VARCHAR(500)   ENCODE lzo
	,order_external_id VARCHAR(5000)   ENCODE lzo
	,order_outcome VARCHAR(500)   ENCODE lzo
	,order_session_id VARCHAR(65535)   ENCODE lzo
	,order_total_amount NUMERIC(20,4)   ENCODE lzo
	,order_amount_in_usd NUMERIC(20,4)   ENCODE lzo
	,platform_order_id VARCHAR(500)   ENCODE lzo
	,purchase_created_at VARCHAR(500)   ENCODE lzo
	,received_by VARCHAR(500)   ENCODE lzo
	,recurring BOOLEAN   ENCODE RAW
	,request_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,risk_assessment_region VARCHAR(500)   ENCODE lzo
	,seller_account_number VARCHAR(500)   ENCODE lzo
	,seller_aggregate_order_count BIGINT   ENCODE lzo
	,seller_aggregate_order_dollars NUMERIC(20,4)   ENCODE lzo
	,seller_corporate_address_street_address VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_unit VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_city VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_postal_code VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_province_code VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_country_code CHAR(4096)   ENCODE lzo
	,seller_corporate_address_full_address VARCHAR(500)   ENCODE lzo
	,seller_corporate_address_latitude DOUBLE PRECISION   ENCODE RAW
	,seller_corporate_address_longitude DOUBLE PRECISION   ENCODE RAW
	,seller_created_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,seller_domain VARCHAR(500)   ENCODE lzo
	,seller_email VARCHAR(500)   ENCODE lzo
	,seller_last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,seller_name VARCHAR(2500)   ENCODE lzo
	,seller_onboarding_ip_address VARCHAR(500)   ENCODE lzo
	,seller_onboarding_email VARCHAR(500)   ENCODE lzo
	,seller_phone VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_street_address VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_unit VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_city VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_postal_code VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_province_code VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_country_code CHAR(4096)   ENCODE lzo
	,seller_ship_from_address_full_address VARCHAR(500)   ENCODE lzo
	,seller_ship_from_address_latitude DOUBLE PRECISION   ENCODE RAW
	,seller_ship_from_address_longitude DOUBLE PRECISION   ENCODE RAW
	,seller_username VARCHAR(500)   ENCODE lzo
	,seller_tags VARCHAR(500)   ENCODE lzo
	,signifyd_client_app VARCHAR(500)   ENCODE lzo
	,signifyd_client_app_version VARCHAR(500)   ENCODE lzo
	,signifyd_score DOUBLE PRECISION   ENCODE RAW
	,store_platform VARCHAR(500)   ENCODE lzo
	,store_platform_version VARCHAR(500)   ENCODE lzo
	,team_id BIGINT   ENCODE RAW
	,transaction_id VARCHAR(500)   ENCODE lzo
	,user_account_aggregate_order_count BIGINT   ENCODE lzo
	,user_account_aggregate_order_dollars NUMERIC(20,4)   ENCODE lzo
	,user_account_last_order_external_id VARCHAR(500)   ENCODE lzo
	,user_account_last_update_date VARCHAR(500)   ENCODE lzo
	,user_account_user_name VARCHAR(1000)   ENCODE lzo
	,user_account_number VARCHAR(500)   ENCODE lzo
	,user_account_created_date VARCHAR(500)   ENCODE lzo
	,raw_user_account_phone VARCHAR(3000)   ENCODE lzo
	,raw_user_account_email VARCHAR(500)   ENCODE lzo
	,user_account_email VARCHAR(500)   ENCODE lzo
	,user_account_phone VARCHAR(500)   ENCODE lzo
	,user_account_email_oh_key VARCHAR(500)   ENCODE lzo
	,user_account_phone_oh_key VARCHAR(500)   ENCODE lzo
	,tags VARCHAR(5000)   ENCODE lzo
	,order_total_amount_currency VARCHAR(500)   ENCODE lzo
	,data_source VARCHAR(500)   ENCODE lzo
	,data_bucket VARCHAR(500)   ENCODE lzo
	,seller_rating VARCHAR(500)   ENCODE lzo
	,user_account_rating VARCHAR(500)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
INTERLEAVED SORTKEY (
	investigation_id
	, created_at
	, team_id
	)
;
--DROP TABLE datalake.investigations_duplicate_records;
CREATE TABLE IF NOT EXISTS datalake.investigations_duplicate_records
(
	investigation_id BIGINT   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
;
--DROP TABLE datalake.investigations_duplicates;
CREATE TABLE IF NOT EXISTS datalake.investigations_duplicates
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
;
--DROP TABLE datalake.investigations_feb18;
CREATE TABLE IF NOT EXISTS datalake.investigations_feb18
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
;
--DROP TABLE datalake.ledger_entries;
CREATE TABLE IF NOT EXISTS datalake.ledger_entries
(
	investigation_id BIGINT   ENCODE RAW
	,ledger_entry_id BIGINT   ENCODE lzo
	,ledger_entry_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,event_status VARCHAR(65535)   ENCODE lzo
	,revenue_usd NUMERIC(20,6)   ENCODE lzo
	,revenue_local NUMERIC(20,6)   ENCODE lzo
	,currency VARCHAR(65535)   ENCODE lzo
	,exchange_rate NUMERIC(20,6)   ENCODE lzo
	,ledger_entry_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,take_rate NUMERIC(20,6)   ENCODE lzo
	,plan_id BIGINT   ENCODE lzo
	,guarantee_amount_local NUMERIC(20,6)   ENCODE lzo
	,guarantee_amount_usd NUMERIC(20,6)   ENCODE lzo
	,claim_id BIGINT   ENCODE lzo
	,chargeback_id BIGINT   ENCODE lzo
	,parent_ledger_entry_id BIGINT   ENCODE lzo
	,accounting_code VARCHAR(30)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.manual_review_timetracking;
CREATE TABLE IF NOT EXISTS datalake.manual_review_timetracking
(
	investigation_id BIGINT NOT NULL  ENCODE RAW
	,guarantee_created_at TIMESTAMP WITH TIME ZONE   ENCODE delta
	,guarantee_review_started_at TIMESTAMP WITH TIME ZONE NOT NULL  ENCODE delta
	,guarantee_review_finished_at TIMESTAMP WITH TIME ZONE   ENCODE delta
	,guarantee_disposition VARCHAR(50)   ENCODE text255
	,reviewed_by BIGINT   ENCODE lzo
	,decision_count SMALLINT   ENCODE mostly8
	,manual_review_entered_at TIMESTAMP WITH TIME ZONE   ENCODE delta
	,guarantee_evented_at TIMESTAMP WITH TIME ZONE   ENCODE delta
	,previous_guarantee_disposition VARCHAR(50)   ENCODE text255
	,reviewer_group_name VARCHAR(50)   ENCODE text255
	,filter_name VARCHAR(50)   ENCODE text255
	,guarantee_review_deadline TIMESTAMP WITH TIME ZONE   ENCODE delta
	,team_id BIGINT   ENCODE lzo
	,order_amount_usd NUMERIC(18,0)   ENCODE lzo
	,sla_in_millis BIGINT   ENCODE lzo
	,risk_assessment_region VARCHAR(256)   ENCODE lzo
	,escalation_level INTEGER   ENCODE lzo
	,signifyd_score DOUBLE PRECISION   ENCODE RAW
	,escalation_recommendation VARCHAR(50)   ENCODE text255
	,PRIMARY KEY (investigation_id, guarantee_review_started_at)
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_address;
CREATE TABLE IF NOT EXISTS datalake.pipl_address
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,address_idx INTEGER   ENCODE lzo
	,address_type VARCHAR(65535)   ENCODE lzo
	,country VARCHAR(65535)   ENCODE lzo
	,state VARCHAR(65535)   ENCODE lzo
	,city VARCHAR(65535)   ENCODE lzo
	,street_name VARCHAR(65535)   ENCODE lzo
	,house VARCHAR(65535)   ENCODE lzo
	,apartment VARCHAR(65535)   ENCODE lzo
	,postal_code VARCHAR(65535)   ENCODE lzo
	,po_box VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_address_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_address_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,address_idx INTEGER NOT NULL  ENCODE lzo
	,address_type VARCHAR(65535)   ENCODE lzo
	,country VARCHAR(65535)   ENCODE lzo
	,state VARCHAR(65535)   ENCODE lzo
	,city VARCHAR(65535)   ENCODE lzo
	,street_name VARCHAR(65535)   ENCODE lzo
	,house VARCHAR(65535)   ENCODE lzo
	,apartment VARCHAR(65535)   ENCODE lzo
	,postal_code VARCHAR(65535)   ENCODE lzo
	,po_box VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_education;
CREATE TABLE IF NOT EXISTS datalake.pipl_education
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,education_idx INTEGER   ENCODE lzo
	,degree VARCHAR(65535)   ENCODE lzo
	,school VARCHAR(65535)   ENCODE lzo
	,education_date_start VARCHAR(65535)   ENCODE lzo
	,education_date_end VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_education_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_education_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,education_idx INTEGER NOT NULL  ENCODE lzo
	,degree VARCHAR(65535)   ENCODE lzo
	,school VARCHAR(65535)   ENCODE lzo
	,education_date_start VARCHAR(65535)   ENCODE lzo
	,education_date_end VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_email;
CREATE TABLE IF NOT EXISTS datalake.pipl_email
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,email_idx INTEGER   ENCODE lzo
	,email_type VARCHAR(65535)   ENCODE lzo
	,address VARCHAR(65535)   ENCODE lzo
	,address_md5 VARCHAR(65535)   ENCODE lzo
	,is_disposable BOOLEAN   ENCODE RAW
	,is_email_provider BOOLEAN   ENCODE RAW
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_email_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_email_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,email_idx INTEGER NOT NULL  ENCODE lzo
	,email_type VARCHAR(65535)   ENCODE lzo
	,address VARCHAR(65535)   ENCODE lzo
	,address_md5 VARCHAR(65535)   ENCODE lzo
	,is_disposable BOOLEAN   ENCODE RAW
	,is_email_provider BOOLEAN   ENCODE RAW
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_image;
CREATE TABLE IF NOT EXISTS datalake.pipl_image
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,image_idx INTEGER   ENCODE lzo
	,url VARCHAR(65535)   ENCODE lzo
	,thumbnail_token VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_image_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_image_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,image_idx INTEGER NOT NULL  ENCODE lzo
	,url VARCHAR(65535)   ENCODE lzo
	,thumbnail_token VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_job;
CREATE TABLE IF NOT EXISTS datalake.pipl_job
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,job_idx INTEGER   ENCODE lzo
	,title VARCHAR(65535)   ENCODE lzo
	,organization VARCHAR(65535)   ENCODE lzo
	,industry VARCHAR(65535)   ENCODE lzo
	,job_date_start VARCHAR(65535)   ENCODE lzo
	,job_date_end VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_job_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_job_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,job_idx INTEGER NOT NULL  ENCODE lzo
	,title VARCHAR(65535)   ENCODE lzo
	,organization VARCHAR(65535)   ENCODE lzo
	,industry VARCHAR(65535)   ENCODE lzo
	,job_date_start VARCHAR(65535)   ENCODE lzo
	,job_date_end VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_language;
CREATE TABLE IF NOT EXISTS datalake.pipl_language
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,language_idx INTEGER   ENCODE lzo
	,language_code VARCHAR(65535)   ENCODE lzo
	,region VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_language_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_language_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,language_idx INTEGER NOT NULL  ENCODE lzo
	,language_code VARCHAR(65535)   ENCODE lzo
	,region VARCHAR(65535)   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_name;
CREATE TABLE IF NOT EXISTS datalake.pipl_name
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,name_idx INTEGER   ENCODE lzo
	,name_type VARCHAR(65535)   ENCODE lzo
	,first_name VARCHAR(65535)   ENCODE lzo
	,middle_name VARCHAR(65535)   ENCODE lzo
	,last_name VARCHAR(65535)   ENCODE lzo
	,name_prefix VARCHAR(65535)   ENCODE lzo
	,name_suffix VARCHAR(65535)   ENCODE lzo
	,display_name VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_name_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_name_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,name_idx INTEGER NOT NULL  ENCODE lzo
	,name_type VARCHAR(65535)   ENCODE lzo
	,first_name VARCHAR(65535)   ENCODE lzo
	,middle_name VARCHAR(65535)   ENCODE lzo
	,last_name VARCHAR(65535)   ENCODE lzo
	,name_prefix VARCHAR(65535)   ENCODE lzo
	,name_suffix VARCHAR(65535)   ENCODE lzo
	,display_name VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_origin_country;
CREATE TABLE IF NOT EXISTS datalake.pipl_origin_country
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,origin_country_idx INTEGER   ENCODE lzo
	,country VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_origin_country_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_origin_country_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,origin_country_idx INTEGER NOT NULL  ENCODE lzo
	,country VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_person;
CREATE TABLE IF NOT EXISTS datalake.pipl_person
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,person_guid VARCHAR(65535)   ENCODE lzo
	,gender VARCHAR(65535)   ENCODE lzo
	,birth_date_start VARCHAR(65535)   ENCODE lzo
	,birth_date_end VARCHAR(65535)   ENCODE lzo
	,birth_date_display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_person_old;
CREATE TABLE IF NOT EXISTS datalake.pipl_person_old
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,person_guid VARCHAR(65535)   ENCODE lzo
	,match_score REAL   ENCODE RAW
	,gender VARCHAR(65535)   ENCODE lzo
	,birth_date_start VARCHAR(65535)   ENCODE lzo
	,birth_date_end VARCHAR(65535)   ENCODE lzo
	,birth_date_display VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_person_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_person_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,person_guid VARCHAR(65535)   ENCODE lzo
	,gender VARCHAR(65535)   ENCODE lzo
	,birth_date_start VARCHAR(65535)   ENCODE lzo
	,birth_date_end VARCHAR(65535)   ENCODE lzo
	,birth_date_display VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_phone;
CREATE TABLE IF NOT EXISTS datalake.pipl_phone
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,phone_idx INTEGER   ENCODE lzo
	,phone_type VARCHAR(65535)   ENCODE lzo
	,country_code VARCHAR(65535)   ENCODE lzo
	,number BIGINT   ENCODE lzo
	,extension BIGINT   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,display_international VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_phone_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_phone_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,phone_idx INTEGER NOT NULL  ENCODE lzo
	,phone_type VARCHAR(65535)   ENCODE lzo
	,country_code VARCHAR(65535)   ENCODE lzo
	,number BIGINT   ENCODE lzo
	,extension BIGINT   ENCODE lzo
	,display VARCHAR(65535)   ENCODE lzo
	,display_international VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_url;
CREATE TABLE IF NOT EXISTS datalake.pipl_url
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,url_idx INTEGER   ENCODE lzo
	,source_id VARCHAR(65535)   ENCODE lzo
	,domain_name VARCHAR(65535)   ENCODE lzo
	,site_name VARCHAR(65535)   ENCODE lzo
	,category VARCHAR(65535)   ENCODE lzo
	,url VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_url_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_url_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,url_idx INTEGER NOT NULL  ENCODE lzo
	,source_id VARCHAR(65535)   ENCODE lzo
	,domain_name VARCHAR(65535)   ENCODE lzo
	,site_name VARCHAR(65535)   ENCODE lzo
	,category VARCHAR(65535)   ENCODE lzo
	,url VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_user_id;
CREATE TABLE IF NOT EXISTS datalake.pipl_user_id
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,user_id_idx INTEGER   ENCODE lzo
	,user_id VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_user_id_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_user_id_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,user_id_idx INTEGER NOT NULL  ENCODE lzo
	,user_id VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.pipl_username;
CREATE TABLE IF NOT EXISTS datalake.pipl_username
(
	investigation_id BIGINT   ENCODE RAW
	,person_idx INTEGER   ENCODE lzo
	,username_idx INTEGER   ENCODE lzo
	,username VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.pipl_username_staging;
CREATE TABLE IF NOT EXISTS datalake.pipl_username_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,person_idx INTEGER NOT NULL  ENCODE lzo
	,username_idx INTEGER NOT NULL  ENCODE lzo
	,username VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.products;
CREATE TABLE IF NOT EXISTS datalake.products
(
	investigation_id BIGINT   ENCODE RAW
	,product_idx INTEGER   ENCODE lzo
	,item_id VARCHAR(65535)   ENCODE lzo
	,item_name VARCHAR(65535)   ENCODE lzo
	,item_url VARCHAR(65535)   ENCODE lzo
	,item_image VARCHAR(65535)   ENCODE lzo
	,item_quantity INTEGER   ENCODE lzo
	,item_price NUMERIC(20,4)   ENCODE lzo
	,item_weight NUMERIC(20,4)   ENCODE lzo
	,item_is_digital BOOLEAN   ENCODE RAW
	,item_category VARCHAR(65535)   ENCODE lzo
	,item_sub_category VARCHAR(65535)   ENCODE lzo
	,department VARCHAR(65535)   ENCODE lzo
	,semantics3_categorize_json VARCHAR(65535)   ENCODE lzo
	,semantics3_product_data_json VARCHAR(65535)   ENCODE lzo
	,seller_account_number VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.purchase_discount_codes;
CREATE TABLE IF NOT EXISTS datalake.purchase_discount_codes
(
	investigation_id BIGINT   ENCODE RAW
	,purchase_discount_code_idx INTEGER   ENCODE lzo
	,amount NUMERIC(20,4)   ENCODE lzo
	,percentage NUMERIC(7,4)   ENCODE lzo
	,code VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.recipients;
CREATE TABLE IF NOT EXISTS datalake.recipients
(
	investigation_id BIGINT   ENCODE RAW
	,recipient_idx INTEGER   ENCODE lzo
	,raw_full_address VARCHAR(65535)   ENCODE lzo
	,raw_street_address VARCHAR(65535)   ENCODE lzo
	,raw_unit VARCHAR(65535)   ENCODE lzo
	,raw_city VARCHAR(65535)   ENCODE lzo
	,raw_province_code VARCHAR(65535)   ENCODE lzo
	,raw_postal_code VARCHAR(65535)   ENCODE lzo
	,raw_country_code VARCHAR(65535)   ENCODE lzo
	,raw_latitude DOUBLE PRECISION   ENCODE RAW
	,raw_longitude DOUBLE PRECISION   ENCODE RAW
	,raw_full_name VARCHAR(65535)   ENCODE lzo
	,raw_confirmation_email VARCHAR(65535)   ENCODE lzo
	,raw_confirmation_phone VARCHAR(65535)   ENCODE lzo
	,raw_organization VARCHAR(65535)   ENCODE lzo
	,confirmation_email VARCHAR(65535)   ENCODE lzo
	,confirmation_phone VARCHAR(65535)   ENCODE lzo
	,street_number_long VARCHAR(65535)   ENCODE lzo
	,post_box_long VARCHAR(65535)   ENCODE lzo
	,premise_long VARCHAR(65535)   ENCODE lzo
	,subpremise_long VARCHAR(65535)   ENCODE lzo
	,floor_long VARCHAR(65535)   ENCODE lzo
	,room_long VARCHAR(65535)   ENCODE lzo
	,route_long VARCHAR(65535)   ENCODE lzo
	,locality_long VARCHAR(65535)   ENCODE lzo
	,sublocality_long VARCHAR(65535)   ENCODE lzo
	,ward_long VARCHAR(65535)   ENCODE lzo
	,admin_area_1_long VARCHAR(65535)   ENCODE lzo
	,admin_area_1_short VARCHAR(65535)   ENCODE lzo
	,admin_area_2_long VARCHAR(65535)   ENCODE lzo
	,admin_area_3_long VARCHAR(65535)   ENCODE lzo
	,admin_area_4_long VARCHAR(65535)   ENCODE lzo
	,admin_area_5_long VARCHAR(65535)   ENCODE lzo
	,country_long VARCHAR(65535)   ENCODE lzo
	,country_short CHAR(4096)   ENCODE lzo
	,postal_code_long VARCHAR(65535)   ENCODE lzo
	,formatted_address VARCHAR(65535)   ENCODE lzo
	,location_type VARCHAR(65535)   ENCODE lzo
	,types VARCHAR(65535)   ENCODE lzo
	,delivery_address_oh_key VARCHAR(65535)   ENCODE lzo
	,confirmation_email_oh_key VARCHAR(65535)   ENCODE lzo
	,confirmation_phone_oh_key VARCHAR(65535)   ENCODE lzo
	,td_email_popularity SMALLINT   ENCODE lzo
	,td_email_velocity SMALLINT   ENCODE lzo
	,td_email_longevity SMALLINT   ENCODE lzo
	,td_email_raw_date_first_seen VARCHAR(65535)   ENCODE lzo
	,td_email_date_first_seen DATE   ENCODE lzo
	,fc_person_by_email_json VARCHAR(65535)   ENCODE lzo
	,fc_person_by_email_status INTEGER   ENCODE lzo
	,fc_company_by_email_json VARCHAR(65535)   ENCODE lzo
	,neighborhood VARCHAR(65535)   ENCODE lzo
	,plus_code VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.recommendation;
CREATE TABLE IF NOT EXISTS datalake.recommendation
(
	investigation_id BIGINT   ENCODE RAW
	,recommended_action VARCHAR(65535)   ENCODE lzo
	,decision_disposition VARCHAR(65535)   ENCODE lzo
	,model_id VARCHAR(65535)   ENCODE lzo
	,model_score DOUBLE PRECISION   ENCODE RAW
	,calibrated_score DOUBLE PRECISION   ENCODE RAW
	,threshold_config_uuid VARCHAR(65535)   ENCODE lzo
	,auto_decision_reason VARCHAR(65535)   ENCODE lzo
	,plan_type VARCHAR(65535)   ENCODE lzo
	,plan_id BIGINT   ENCODE lzo
	,auto_submission_info_id BIGINT   ENCODE lzo
	,auto_submission_info_policy_name VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.representment_charges;
CREATE TABLE IF NOT EXISTS datalake.representment_charges
(
	investigation_id BIGINT   ENCODE RAW
	,representment_id BIGINT   ENCODE lzo
	,invoice_id VARCHAR(255)   ENCODE lzo
	,invoice_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.representment_charges_staging;
CREATE TABLE IF NOT EXISTS datalake.representment_charges_staging
(
	investigation_id BIGINT NOT NULL  ENCODE lzo
	,representment_id BIGINT   ENCODE lzo
	,invoice_id VARCHAR(65535)   ENCODE lzo
	,invoice_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
<<Error - UNKNOWN DISTSTYLE>>
;
--DROP TABLE datalake.representment_notes;
CREATE TABLE IF NOT EXISTS datalake.representment_notes
(
	investigation_id BIGINT   ENCODE RAW
	,representment_note_id BIGINT   ENCODE lzo
	,representment_id BIGINT   ENCODE lzo
	,text VARCHAR(65535)   ENCODE lzo
	,created_by BIGINT   ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.representment_timetrackings;
CREATE TABLE IF NOT EXISTS datalake.representment_timetrackings
(
	representment_id BIGINT NOT NULL  ENCODE RAW
	,closed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,arbitration_cb_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,arbitration_decision_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_abandon_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_assigned_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_cb_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_decision_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_dispute_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_disputed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,chargeback_review_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_abandon_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_assigned_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_cb_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_decision_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_dispute_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_disputed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,prearbitration_review_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_abandon_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_assigned_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_cb_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_decision_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_dispute_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_disputed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,retrieval_review_start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,last_updated_field VARCHAR(127) NOT NULL  ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp with time zone ENCODE lzo
	,updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp with time zone ENCODE lzo
	,PRIMARY KEY (representment_id)
)
DISTSTYLE KEY
 DISTKEY (representment_id)
 SORTKEY (
	representment_id
	)
;
--DROP TABLE datalake.sellers;
CREATE TABLE IF NOT EXISTS datalake.sellers
(
	investigation_id BIGINT   ENCODE RAW
	,seller_idx INTEGER   ENCODE lzo
	,account_number VARCHAR(65535)   ENCODE lzo
	,aggregate_order_count BIGINT   ENCODE lzo
	,aggregate_order_dollars NUMERIC(20,4)   ENCODE lzo
	,corporate_address_street_address VARCHAR(65535)   ENCODE lzo
	,corporate_address_unit VARCHAR(65535)   ENCODE lzo
	,corporate_address_city VARCHAR(65535)   ENCODE lzo
	,corporate_address_postal_code VARCHAR(65535)   ENCODE lzo
	,corporate_address_province_code VARCHAR(65535)   ENCODE lzo
	,corporate_address_country_code CHAR(4096)   ENCODE lzo
	,corporate_address_full_address VARCHAR(65535)   ENCODE lzo
	,corporate_address_latitude DOUBLE PRECISION   ENCODE RAW
	,corporate_address_longitude DOUBLE PRECISION   ENCODE RAW
	,created_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,domain VARCHAR(65535)   ENCODE lzo
	,email VARCHAR(65535)   ENCODE lzo
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,name VARCHAR(65535)   ENCODE lzo
	,onboarding_ip_address VARCHAR(65535)   ENCODE lzo
	,onboarding_email VARCHAR(65535)   ENCODE lzo
	,phone VARCHAR(65535)   ENCODE lzo
	,ship_from_address_street_address VARCHAR(65535)   ENCODE lzo
	,ship_from_address_unit VARCHAR(65535)   ENCODE lzo
	,ship_from_address_city VARCHAR(65535)   ENCODE lzo
	,ship_from_address_postal_code VARCHAR(65535)   ENCODE lzo
	,ship_from_address_province_code VARCHAR(65535)   ENCODE lzo
	,ship_from_address_country_code CHAR(4096)   ENCODE lzo
	,ship_from_address_full_address VARCHAR(65535)   ENCODE lzo
	,ship_from_address_latitude DOUBLE PRECISION   ENCODE RAW
	,ship_from_address_longitude DOUBLE PRECISION   ENCODE RAW
	,username VARCHAR(65535)   ENCODE lzo
	,tags VARCHAR(65535)   ENCODE lzo
	,rating VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.session_metadata;
CREATE TABLE IF NOT EXISTS datalake.session_metadata
(
	investigation_id BIGINT   ENCODE RAW
	,browser_id VARCHAR(65535)   ENCODE lzo
	,session_id VARCHAR(65535)   ENCODE lzo
	,timestamp BIGINT   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.shipments;
CREATE TABLE IF NOT EXISTS datalake.shipments
(
	investigation_id BIGINT   ENCODE RAW
	,shipment_idx INTEGER   ENCODE lzo
	,shipping_price NUMERIC(20,4)   ENCODE lzo
	,shipper VARCHAR(65535)   ENCODE lzo
	,shipping_method VARCHAR(65535)   ENCODE lzo
	,tracking_number VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.threat_metrix;
CREATE TABLE IF NOT EXISTS datalake.threat_metrix
(
	investigation_id BIGINT   ENCODE RAW
	,agent_type VARCHAR(65535)   ENCODE lzo
	,api_call_datetime TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,api_version VARCHAR(65535)   ENCODE lzo
	,browser VARCHAR(65535)   ENCODE lzo
	,browser_string VARCHAR(65535)   ENCODE lzo
	,browser_version VARCHAR(65535)   ENCODE lzo
	,css_image_loaded VARCHAR(65535)   ENCODE lzo
	,device_first_seen DATE   ENCODE lzo
	,device_id VARCHAR(65535)   ENCODE lzo
	,device_id_confidence NUMERIC(5,2)   ENCODE lzo
	,device_match_result VARCHAR(65535)   ENCODE lzo
	,device_result VARCHAR(65535)   ENCODE lzo
	,dns_ip VARCHAR(65535)   ENCODE lzo
	,dns_ip_city VARCHAR(65535)   ENCODE lzo
	,dns_ip_geo CHAR(4096)   ENCODE lzo
	,dns_ip_isp VARCHAR(65535)   ENCODE lzo
	,dns_ip_latitude DOUBLE PRECISION   ENCODE bytedict
	,dns_ip_longitude DOUBLE PRECISION   ENCODE bytedict
	,dns_ip_organization VARCHAR(65535)   ENCODE lzo
	,dns_ip_region CHAR(4096)   ENCODE bytedict
	,dns_ip_region_iso_code VARCHAR(65535)   ENCODE lzo
	,enabled_ck VARCHAR(65535)   ENCODE lzo
	,enabled_fl VARCHAR(65535)   ENCODE lzo
	,enabled_im VARCHAR(65535)   ENCODE lzo
	,enabled_js VARCHAR(65535)   ENCODE lzo
	,event_type VARCHAR(65535)   ENCODE lzo
	,fuzzy_device_first_seen DATE   ENCODE lzo
	,fuzzy_device_id VARCHAR(65535)   ENCODE lzo
	,fuzzy_device_id_confidence NUMERIC(5,2)   ENCODE lzo
	,fuzzy_device_last_event DATE   ENCODE lzo
	,fuzzy_device_last_update DATE   ENCODE lzo
	,fuzzy_device_match_result VARCHAR(65535)   ENCODE lzo
	,fuzzy_device_result VARCHAR(65535)   ENCODE lzo
	,fuzzy_device_score INTEGER   ENCODE lzo
	,fuzzy_device_worst_score INTEGER   ENCODE lzo
	,headers_name_value_hash VARCHAR(65535)   ENCODE lzo
	,headers_order_string_hash VARCHAR(65535)   ENCODE lzo
	,http_os_signature VARCHAR(65535)   ENCODE lzo
	,http_referer VARCHAR(65535)   ENCODE lzo
	,http_referer_domain VARCHAR(65535)   ENCODE lzo
	,http_referer_url VARCHAR(65535)   ENCODE lzo
	,image_loaded VARCHAR(65535)   ENCODE lzo
	,js_browser VARCHAR(65535)   ENCODE lzo
	,js_browser_string VARCHAR(65535)   ENCODE lzo
	,js_browser_string_hash VARCHAR(65535)   ENCODE lzo
	,js_fonts_hash VARCHAR(65535)   ENCODE lzo
	,js_fonts_number INTEGER   ENCODE lzo
	,js_os CHAR(4096)   ENCODE bytedict
	,mime_type_hash VARCHAR(65535)   ENCODE lzo
	,mime_type_number INTEGER   ENCODE lzo
	,org_id VARCHAR(65535)   ENCODE lzo
	,os VARCHAR(65535)   ENCODE lzo
	,os_version VARCHAR(65535)   ENCODE lzo
	,page_time_on BIGINT   ENCODE lzo
	,plugin_hash VARCHAR(65535)   ENCODE lzo
	,plugin_number INTEGER   ENCODE lzo
	,policy VARCHAR(65535)   ENCODE lzo
	,policy_score INTEGER   ENCODE lzo
	,profiled_domain VARCHAR(65535)   ENCODE lzo
	,profiled_url VARCHAR(65535)   ENCODE lzo
	,profiling_datetime BIGINT   ENCODE lzo
	,reason_code VARCHAR(65535)   ENCODE lzo
	,request_duration INTEGER   ENCODE lzo
	,request_id VARCHAR(65535)   ENCODE lzo
	,request_result VARCHAR(65535)   ENCODE lzo
	,review_status VARCHAR(65535)   ENCODE lzo
	,risk_rating VARCHAR(65535)   ENCODE lzo
	,screen_color_depth INTEGER   ENCODE lzo
	,screen_res CHAR(4096)   ENCODE bytedict
	,service_type VARCHAR(65535)   ENCODE lzo
	,session_anomaly VARCHAR(65535)   ENCODE lzo
	,session_id VARCHAR(65535)   ENCODE lzo
	,session_id_query_count INTEGER   ENCODE lzo
	,summary_risk_score INTEGER   ENCODE lzo
	,time_zone INTEGER   ENCODE lzo
	,time_zone_dst_offset INTEGER   ENCODE lzo
	,true_ip_attributes VARCHAR(65535)   ENCODE lzo
	,true_ip_city VARCHAR(65535)   ENCODE lzo
	,true_ip_first_seen DATE   ENCODE lzo
	,true_ip_geo VARCHAR(65535)   ENCODE lzo
	,true_ip_isp VARCHAR(65535)   ENCODE lzo
	,true_ip_last_event DATE   ENCODE lzo
	,true_ip_last_update DATE   ENCODE lzo
	,true_ip VARCHAR(65535)   ENCODE lzo
	,true_ip_latitude DOUBLE PRECISION   ENCODE RAW
	,true_ip_longitude DOUBLE PRECISION   ENCODE RAW
	,true_ip_organization VARCHAR(65535)   ENCODE lzo
	,true_ip_region CHAR(4096)   ENCODE bytedict
	,true_ip_region_iso_code VARCHAR(65535)   ENCODE lzo
	,true_ip_score BIGINT   ENCODE lzo
	,true_ip_worst_score BIGINT   ENCODE lzo
	,ua_agent VARCHAR(65535)   ENCODE lzo
	,ua_browser VARCHAR(65535)   ENCODE lzo
	,ua_mobile VARCHAR(65535)   ENCODE lzo
	,ua_os VARCHAR(65535)   ENCODE lzo
	,ua_platform VARCHAR(65535)   ENCODE lzo
	,device_id_oh_key VARCHAR(65535)   ENCODE lzo
	,remaining_fields_json VARCHAR(65535)   ENCODE lzo
	,unknown_session VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.threeds_authentication;
CREATE TABLE IF NOT EXISTS datalake.threeds_authentication
(
	investigation_id BIGINT   ENCODE RAW
	,threeds_requestor_id VARCHAR(65535)   ENCODE lzo
	,threeds_requestor_name VARCHAR(65535)   ENCODE lzo
	,threeds_requestor_url VARCHAR(65535)   ENCODE lzo
	,acquirer_bin VARCHAR(65535)   ENCODE lzo
	,acquirer_merchant_id VARCHAR(65535)   ENCODE lzo
	,addr_match VARCHAR(65535)   ENCODE lzo
	,card_expiry_date VARCHAR(65535)   ENCODE lzo
	,bill_addr_city VARCHAR(65535)   ENCODE lzo
	,bill_addr_country VARCHAR(65535)   ENCODE lzo
	,bill_addr_line1 VARCHAR(65535)   ENCODE lzo
	,bill_addr_line2 VARCHAR(65535)   ENCODE lzo
	,bill_addr_line3 VARCHAR(65535)   ENCODE lzo
	,bill_addr_post_code VARCHAR(65535)   ENCODE lzo
	,bill_addr_state VARCHAR(65535)   ENCODE lzo
	,email VARCHAR(65535)   ENCODE lzo
	,home_phone_country_code VARCHAR(65535)   ENCODE lzo
	,home_phone_subscriber VARCHAR(65535)   ENCODE lzo
	,mobile_phone_country_code VARCHAR(65535)   ENCODE lzo
	,mobile_phone_subscriber VARCHAR(65535)   ENCODE lzo
	,cardholder_name VARCHAR(65535)   ENCODE lzo
	,ship_addr_city VARCHAR(65535)   ENCODE lzo
	,ship_addr_country VARCHAR(65535)   ENCODE lzo
	,ship_addr_line1 VARCHAR(65535)   ENCODE lzo
	,ship_addr_line2 VARCHAR(65535)   ENCODE lzo
	,ship_addr_line3 VARCHAR(65535)   ENCODE lzo
	,ship_addr_post_code VARCHAR(65535)   ENCODE lzo
	,ship_addr_state VARCHAR(65535)   ENCODE lzo
	,work_phone_country_code VARCHAR(65535)   ENCODE lzo
	,work_phone_subscriber VARCHAR(65535)   ENCODE lzo
	,device_channel VARCHAR(65535)   ENCODE lzo
	,sdk_interface VARCHAR(65535)   ENCODE lzo
	,sdk_ui_types VARCHAR(65535)   ENCODE lzo
	,mcc VARCHAR(65535)   ENCODE lzo
	,merchant_country_code VARCHAR(65535)   ENCODE lzo
	,merchant_name VARCHAR(65535)   ENCODE lzo
	,message_category VARCHAR(65535)   ENCODE lzo
	,req_message_type VARCHAR(65535)   ENCODE lzo
	,req_message_version VARCHAR(65535)   ENCODE lzo
	,purchase_amount VARCHAR(65535)   ENCODE lzo
	,purchase_currency VARCHAR(65535)   ENCODE lzo
	,purchase_exponent VARCHAR(65535)   ENCODE lzo
	,purchase_date VARCHAR(65535)   ENCODE lzo
	,sdk_app_id VARCHAR(65535)   ENCODE lzo
	,sdk_max_timeout VARCHAR(65535)   ENCODE lzo
	,sdk_ephem_pub_key_kty VARCHAR(65535)   ENCODE lzo
	,sdk_ephem_pub_key_crv VARCHAR(65535)   ENCODE lzo
	,sdk_ephem_pub_key_x VARCHAR(65535)   ENCODE lzo
	,sdk_ephem_pub_key_y VARCHAR(65535)   ENCODE lzo
	,sdk_reference_number VARCHAR(65535)   ENCODE lzo
	,sdk_trans_id VARCHAR(65535)   ENCODE lzo
	,trans_type VARCHAR(65535)   ENCODE lzo
	,threeds_server_url VARCHAR(65535)   ENCODE lzo
	,req_threeds_server_trans_id VARCHAR(65535)   ENCODE lzo
	,threeds_server_ref_number VARCHAR(65535)   ENCODE lzo
	,threeds_requestor_authentication_ind VARCHAR(65535)   ENCODE lzo
	,threeds_req_auth_method VARCHAR(65535)   ENCODE lzo
	,threeds_req_auth_timestamp VARCHAR(65535)   ENCODE lzo
	,threeds_req_auth_data VARCHAR(65535)   ENCODE lzo
	,threeds_requestor_challenge_ind VARCHAR(65535)   ENCODE lzo
	,threeds_req_prior_ref VARCHAR(65535)   ENCODE lzo
	,threeds_req_prior_auth_method VARCHAR(65535)   ENCODE lzo
	,threeds_req_prior_auth_timestamp VARCHAR(65535)   ENCODE lzo
	,threeds_req_prior_auth_data VARCHAR(65535)   ENCODE lzo
	,threeds_server_operator_id VARCHAR(65535)   ENCODE lzo
	,acct_type VARCHAR(65535)   ENCODE lzo
	,ch_acc_age_ind VARCHAR(65535)   ENCODE lzo
	,ch_acc_date VARCHAR(65535)   ENCODE lzo
	,ch_acc_change_ind VARCHAR(65535)   ENCODE lzo
	,ch_acc_change VARCHAR(65535)   ENCODE lzo
	,ch_acc_pw_change_ind VARCHAR(65535)   ENCODE lzo
	,ch_acc_pw_change VARCHAR(65535)   ENCODE lzo
	,ship_address_usage_ind VARCHAR(65535)   ENCODE lzo
	,ship_address_usage VARCHAR(65535)   ENCODE lzo
	,txn_activity_day VARCHAR(65535)   ENCODE lzo
	,txn_activity_year VARCHAR(65535)   ENCODE lzo
	,provision_attempts_day VARCHAR(65535)   ENCODE lzo
	,nb_purchase_account VARCHAR(65535)   ENCODE lzo
	,suspicious_acc_activity VARCHAR(65535)   ENCODE lzo
	,ship_name_indicator VARCHAR(65535)   ENCODE lzo
	,payment_acc_ind VARCHAR(65535)   ENCODE lzo
	,payment_acc_age VARCHAR(65535)   ENCODE lzo
	,acct_id VARCHAR(65535)   ENCODE lzo
	,req_ds_reference_number VARCHAR(65535)   ENCODE lzo
	,req_ds_trans_id VARCHAR(65535)   ENCODE lzo
	,ds_url VARCHAR(65535)   ENCODE lzo
	,pay_token_ind BOOLEAN   ENCODE RAW
	,purchase_instal_data VARCHAR(65535)   ENCODE lzo
	,ship_indicator VARCHAR(65535)   ENCODE lzo
	,delivery_timeframe VARCHAR(65535)   ENCODE lzo
	,delivery_email_address VARCHAR(65535)   ENCODE lzo
	,reorder_items_ind VARCHAR(65535)   ENCODE lzo
	,pre_order_purchase_ind VARCHAR(65535)   ENCODE lzo
	,pre_order_date VARCHAR(65535)   ENCODE lzo
	,gift_card_amount VARCHAR(65535)   ENCODE lzo
	,gift_card_curr VARCHAR(65535)   ENCODE lzo
	,gift_card_count VARCHAR(65535)   ENCODE lzo
	,message_extensions VARCHAR(65535)   ENCODE lzo
	,recurring_expiry VARCHAR(65535)   ENCODE lzo
	,recurring_frequency VARCHAR(65535)   ENCODE lzo
	,broad_info_message VARCHAR(65535)   ENCODE lzo
	,browser_java_enabled BOOLEAN   ENCODE RAW
	,res_ds_reference_number VARCHAR(65535)   ENCODE lzo
	,acs_reference_number VARCHAR(65535)   ENCODE lzo
	,acs_trans_id VARCHAR(65535)   ENCODE lzo
	,res_message_type VARCHAR(65535)   ENCODE lzo
	,res_ds_trans_id VARCHAR(65535)   ENCODE lzo
	,acs_operator_id VARCHAR(65535)   ENCODE lzo
	,eci VARCHAR(65535)   ENCODE lzo
	,res_message_version VARCHAR(65535)   ENCODE lzo
	,authentication_value VARCHAR(65535)   ENCODE lzo
	,trans_status VARCHAR(65535)   ENCODE lzo
	,res_threeds_server_trans_id VARCHAR(65535)   ENCODE lzo
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
--DROP TABLE datalake.transactions;
CREATE TABLE IF NOT EXISTS datalake.transactions
(
	investigation_id BIGINT NOT NULL  ENCODE RAW
	,transaction_idx VARCHAR(65535)   ENCODE lzo
	,parent_transaction_id VARCHAR(65535)   ENCODE lzo
	,transaction_id VARCHAR(65535)   ENCODE lzo
	,created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,raw_payment_gateway VARCHAR(65535)   ENCODE lzo
	,raw_payment_method VARCHAR(65535)   ENCODE lzo
	,payment_gateway VARCHAR(65535)   ENCODE lzo
	,payment_method VARCHAR(65535)   ENCODE lzo
	,type VARCHAR(65535)   ENCODE lzo
	,gateway_status_code VARCHAR(65535)   ENCODE lzo
	,gateway_status_message VARCHAR(65535)   ENCODE lzo
	,gateway_error_code VARCHAR(65535)   ENCODE lzo
	,amount NUMERIC(20,4)   ENCODE lzo
	,amount_in_usd NUMERIC(20,4)   ENCODE lzo
	,currency VARCHAR(65535)   ENCODE lzo
	,avs_response_code VARCHAR(65535)   ENCODE lzo
	,cvv_response_code CHAR(4096)   ENCODE lzo
	,paypal_pending_reason_code VARCHAR(65535)   ENCODE lzo
	,paypal_protection_eligibility VARCHAR(65535)   ENCODE lzo
	,paypal_protection_eligibility_type VARCHAR(65535)   ENCODE lzo
	,card_holder_name VARCHAR(65535)   ENCODE lzo
	,card_raw_bin VARCHAR(65535)   ENCODE lzo
	,card_bin INTEGER   ENCODE lzo
	,card_raw_last_four_digits VARCHAR(65535)   ENCODE lzo
	,card_last_four_digits INTEGER   ENCODE lzo
	,card_expiry_month INTEGER   ENCODE lzo
	,card_expiry_year INTEGER   ENCODE lzo
	,bank_account_number VARCHAR(65535)   ENCODE lzo
	,bank_routing_number VARCHAR(65535)   ENCODE lzo
	,bindb_bin INTEGER   ENCODE lzo
	,bindb_brand VARCHAR(65535)   ENCODE lzo
	,bindb_bank VARCHAR(65535)   ENCODE lzo
	,bindb_card_type VARCHAR(65535)   ENCODE lzo
	,bindb_card_level VARCHAR(65535)   ENCODE lzo
	,bindb_country VARCHAR(65535)   ENCODE lzo
	,bindb_info VARCHAR(65535)   ENCODE lzo
	,bindb_country_iso CHAR(4096)   ENCODE lzo
	,bindb_country2_iso CHAR(4096)   ENCODE lzo
	,bindb_country3_iso CHAR(4096)   ENCODE lzo
	,bindb_phone VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_city VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_country_code VARCHAR(4096)   ENCODE lzo
	,raw_billing_address_full_address VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_latitude DOUBLE PRECISION   ENCODE RAW
	,raw_billing_address_longitude DOUBLE PRECISION   ENCODE RAW
	,raw_billing_address_province_code VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_postal_code VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_street_address VARCHAR(65535)   ENCODE lzo
	,raw_billing_address_unit VARCHAR(65535)   ENCODE lzo
	,billing_address_street_number_long VARCHAR(65535)   ENCODE lzo
	,billing_address_post_box_long VARCHAR(65535)   ENCODE lzo
	,billing_address_premise_long VARCHAR(65535)   ENCODE lzo
	,billing_address_subpremise_long VARCHAR(65535)   ENCODE lzo
	,billing_address_floor_long VARCHAR(65535)   ENCODE lzo
	,billing_address_room_long VARCHAR(65535)   ENCODE lzo
	,billing_address_route_long VARCHAR(65535)   ENCODE lzo
	,billing_address_locality_long VARCHAR(65535)   ENCODE lzo
	,billing_address_sublocality_long VARCHAR(65535)   ENCODE lzo
	,billing_address_ward_long VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_1_long VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_1_short VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_2_long VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_3_long VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_4_long VARCHAR(65535)   ENCODE lzo
	,billing_address_admin_area_5_long VARCHAR(65535)   ENCODE lzo
	,billing_address_country_long VARCHAR(65535)   ENCODE lzo
	,billing_address_country_short CHAR(4096)   ENCODE lzo
	,billing_address_postal_code_long VARCHAR(65535)   ENCODE lzo
	,billing_address_formatted_address VARCHAR(65535)   ENCODE lzo
	,billing_address_location_type VARCHAR(65535)   ENCODE lzo
	,billing_address_types VARCHAR(65535)   ENCODE lzo
	,billing_address_oh_key VARCHAR(65535)   ENCODE lzo
	,account_created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE lzo
	,account_id VARCHAR(65535)   ENCODE lzo
	,account_holder_name VARCHAR(65535)   ENCODE lzo
	,account_holder_raw_phone VARCHAR(65535)   ENCODE lzo
	,account_holder_phone VARCHAR(65535)   ENCODE lzo
	,account_holder_raw_email VARCHAR(65535)   ENCODE lzo
	,account_holder_email VARCHAR(65535)   ENCODE lzo
	,account_holder_dob VARCHAR(65535)   ENCODE lzo
	,account_holder_annual_income NUMERIC(20,4)   ENCODE lzo
	,account_is_verified BOOLEAN   ENCODE RAW
	,account_is_active BOOLEAN   ENCODE RAW
	,account_credit_line NUMERIC(20,4)   ENCODE lzo
	,account_balance NUMERIC(20,4)   ENCODE lzo
	,account_raw_billing_address_city VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_country_code VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_full_address VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_latitude DOUBLE PRECISION   ENCODE RAW
	,account_raw_billing_address_longitude DOUBLE PRECISION   ENCODE RAW
	,account_raw_billing_address_province_code VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_postal_code VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_street_address VARCHAR(65535)   ENCODE lzo
	,account_raw_billing_address_unit VARCHAR(65535)   ENCODE lzo
	,billing_address_neighborhood VARCHAR(65535)   ENCODE lzo
	,billing_address_plus_code VARCHAR(65535)   ENCODE lzo
	,PRIMARY KEY (investigation_id)
)
DISTSTYLE KEY
 DISTKEY (investigation_id)
 SORTKEY (
	investigation_id
	)
;
